site_name: User Behavior Insights
site_url: https://www.ubisearch.dev
theme:
  name: material
  palette:
    primary: blue
nav:
  - Home: index.md
  - News: news.md
  - The UBI Standard: standard.md
  - Tools and Plugins: tools.md
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/o19s/ubi
  generator: false
copyright: Copyright &copy; 2024 OpenSource Connections
repo_url: https://github.com/o19s/ubi